- id: settings-doc-markdown
  name: Generate settings-doc Markdown
  description: This hook generates a Markdown documentation from pydantic.BaseSettings to a file.
  entry: settings-doc generate --output-format markdown
  language: python
  types: [file, python]
  pass_filenames: false
- id: settings-doc-dotenv
  name: Generate settings-doc .env
  description: This hook generates a .env template from pydantic.BaseSettings to a file.
  entry: settings-doc generate --output-format dotenv
  language: python
  types: [file, python]
  pass_filenames: false